const router=require('express').Router()
const passport=require('passport')
const dotenv=require('dotenv')
dotenv.config()
const middleWare=require("../controllers/middleWare")
const {OAuth2Client}=require('google-auth-library')
const User=require('../models/userSchema')
const userControllers=require('../controllers/userControllers')
router.post("/",userControllers.addUser)
router.post("/register",userControllers.userEmail)
router.post("/login",userControllers.login)
router.get("/getProfile",middleWare.auth,userControllers.getData)
router.get("/getProducts",userControllers.getProducts)
router.get("/getOrders",middleWare.auth,userControllers.getOrders)
router.get("/getSellers",userControllers.getSellers)

module.exports=router